# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AlgoInterface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AlgoInterface.proto',
  package='Algorithms',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x41lgoInterface.proto\x12\nAlgorithms\"*\n\x12ROICoordinatesType\x12\t\n\x01X\x18\x01 \x01(\x05\x12\t\n\x01Y\x18\x02 \x01(\x05\"\"\n\nLDmidpoint\x12\t\n\x01X\x18\x01 \x01(\x05\x12\t\n\x01Y\x18\x02 \x01(\x05\"\\\n\x0cLanePropType\x12\x10\n\x08Lanetype\x18\x01 \x01(\t\x12\x0f\n\x07Lanepos\x18\x02 \x01(\t\x12\x15\n\ravg_intensity\x18\x03 \x01(\x05\x12\x12\n\nmarkingPos\x18\x04 \x01(\x05\";\n\nObjectType\x12\x14\n\x0cobject_class\x18\x01 \x01(\t\x12\x17\n\x0fobject_subclass\x18\x02 \x01(\t\"\x85\x01\n\tImageType\x12\x11\n\timageData\x18\x01 \x01(\x0c\x12\x0e\n\x06Hieght\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x11\n\thistogram\x18\x04 \x01(\x08\x12\r\n\x05gamma\x18\x05 \x01(\x02\x12\x10\n\x08\x63ontrast\x18\x06 \x01(\x02\x12\x12\n\nbrightness\x18\x07 \x01(\x02\"\x8f\x02\n\x0bObjAttrType\x12\x0f\n\x07trackID\x18\x01 \x01(\x05\x12$\n\x04type\x18\x02 \x01(\x0b\x32\x16.Algorithms.ObjectType\x12+\n\x03ROI\x18\x03 \x03(\x0b\x32\x1e.Algorithms.ROICoordinatesType\x12(\n\x08midpoint\x18\x04 \x01(\x0b\x32\x16.Algorithms.LDmidpoint\x12\r\n\x05shape\x18\x05 \x01(\t\x12\x18\n\x10hasUserCorrected\x18\x06 \x01(\x05\x12&\n\x04lane\x18\x07 \x01(\x0b\x32\x18.Algorithms.LanePropType\x12\x13\n\x0btrackername\x18\x08 \x01(\t\x12\x0c\n\x04mask\x18\t \x01(\x0c\"1\n\tEventType\x12\x11\n\teventName\x18\x01 \x01(\t\x12\x11\n\teventData\x18\x02 \x01(\t\"y\n\x0cLabelRequest\x12\x13\n\x0brequestType\x18\x01 \x01(\t\x12,\n\x0b\x43urrentAttr\x18\x02 \x03(\x0b\x32\x17.Algorithms.ObjAttrType\x12&\n\x07NextImg\x18\x03 \x01(\x0b\x32\x15.Algorithms.ImageType\"s\n\rLabelResponse\x12)\n\x08NextAttr\x18\x01 \x03(\x0b\x32\x17.Algorithms.ObjAttrType\x12$\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x15.Algorithms.EventType\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"\x1c\n\tAlgoState\x12\x0f\n\x07isReady\x18\x01 \x01(\x08\x42\x02H\x01\x62\x06proto3')
)




_ROICOORDINATESTYPE = _descriptor.Descriptor(
  name='ROICoordinatesType',
  full_name='Algorithms.ROICoordinatesType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Algorithms.ROICoordinatesType.X', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Algorithms.ROICoordinatesType.Y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=77,
)


_LDMIDPOINT = _descriptor.Descriptor(
  name='LDmidpoint',
  full_name='Algorithms.LDmidpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='Algorithms.LDmidpoint.X', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='Algorithms.LDmidpoint.Y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=113,
)


_LANEPROPTYPE = _descriptor.Descriptor(
  name='LanePropType',
  full_name='Algorithms.LanePropType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Lanetype', full_name='Algorithms.LanePropType.Lanetype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Lanepos', full_name='Algorithms.LanePropType.Lanepos', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_intensity', full_name='Algorithms.LanePropType.avg_intensity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='markingPos', full_name='Algorithms.LanePropType.markingPos', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=207,
)


_OBJECTTYPE = _descriptor.Descriptor(
  name='ObjectType',
  full_name='Algorithms.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_class', full_name='Algorithms.ObjectType.object_class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_subclass', full_name='Algorithms.ObjectType.object_subclass', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=268,
)


_IMAGETYPE = _descriptor.Descriptor(
  name='ImageType',
  full_name='Algorithms.ImageType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageData', full_name='Algorithms.ImageType.imageData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Hieght', full_name='Algorithms.ImageType.Hieght', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Algorithms.ImageType.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='histogram', full_name='Algorithms.ImageType.histogram', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='Algorithms.ImageType.gamma', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contrast', full_name='Algorithms.ImageType.contrast', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='Algorithms.ImageType.brightness', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=404,
)


_OBJATTRTYPE = _descriptor.Descriptor(
  name='ObjAttrType',
  full_name='Algorithms.ObjAttrType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackID', full_name='Algorithms.ObjAttrType.trackID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Algorithms.ObjAttrType.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ROI', full_name='Algorithms.ObjAttrType.ROI', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='midpoint', full_name='Algorithms.ObjAttrType.midpoint', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='Algorithms.ObjAttrType.shape', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hasUserCorrected', full_name='Algorithms.ObjAttrType.hasUserCorrected', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane', full_name='Algorithms.ObjAttrType.lane', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackername', full_name='Algorithms.ObjAttrType.trackername', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mask', full_name='Algorithms.ObjAttrType.mask', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=678,
)


_EVENTTYPE = _descriptor.Descriptor(
  name='EventType',
  full_name='Algorithms.EventType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventName', full_name='Algorithms.EventType.eventName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventData', full_name='Algorithms.EventType.eventData', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=680,
  serialized_end=729,
)


_LABELREQUEST = _descriptor.Descriptor(
  name='LabelRequest',
  full_name='Algorithms.LabelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestType', full_name='Algorithms.LabelRequest.requestType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CurrentAttr', full_name='Algorithms.LabelRequest.CurrentAttr', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NextImg', full_name='Algorithms.LabelRequest.NextImg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=731,
  serialized_end=852,
)


_LABELRESPONSE = _descriptor.Descriptor(
  name='LabelResponse',
  full_name='Algorithms.LabelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='NextAttr', full_name='Algorithms.LabelResponse.NextAttr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='Algorithms.LabelResponse.event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Algorithms.LabelResponse.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=854,
  serialized_end=969,
)


_ALGOSTATE = _descriptor.Descriptor(
  name='AlgoState',
  full_name='Algorithms.AlgoState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isReady', full_name='Algorithms.AlgoState.isReady', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=971,
  serialized_end=999,
)

_OBJATTRTYPE.fields_by_name['type'].message_type = _OBJECTTYPE
_OBJATTRTYPE.fields_by_name['ROI'].message_type = _ROICOORDINATESTYPE
_OBJATTRTYPE.fields_by_name['midpoint'].message_type = _LDMIDPOINT
_OBJATTRTYPE.fields_by_name['lane'].message_type = _LANEPROPTYPE
_LABELREQUEST.fields_by_name['CurrentAttr'].message_type = _OBJATTRTYPE
_LABELREQUEST.fields_by_name['NextImg'].message_type = _IMAGETYPE
_LABELRESPONSE.fields_by_name['NextAttr'].message_type = _OBJATTRTYPE
_LABELRESPONSE.fields_by_name['event'].message_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['ROICoordinatesType'] = _ROICOORDINATESTYPE
DESCRIPTOR.message_types_by_name['LDmidpoint'] = _LDMIDPOINT
DESCRIPTOR.message_types_by_name['LanePropType'] = _LANEPROPTYPE
DESCRIPTOR.message_types_by_name['ObjectType'] = _OBJECTTYPE
DESCRIPTOR.message_types_by_name['ImageType'] = _IMAGETYPE
DESCRIPTOR.message_types_by_name['ObjAttrType'] = _OBJATTRTYPE
DESCRIPTOR.message_types_by_name['EventType'] = _EVENTTYPE
DESCRIPTOR.message_types_by_name['LabelRequest'] = _LABELREQUEST
DESCRIPTOR.message_types_by_name['LabelResponse'] = _LABELRESPONSE
DESCRIPTOR.message_types_by_name['AlgoState'] = _ALGOSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ROICoordinatesType = _reflection.GeneratedProtocolMessageType('ROICoordinatesType', (_message.Message,), dict(
  DESCRIPTOR = _ROICOORDINATESTYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.ROICoordinatesType)
  ))
_sym_db.RegisterMessage(ROICoordinatesType)

LDmidpoint = _reflection.GeneratedProtocolMessageType('LDmidpoint', (_message.Message,), dict(
  DESCRIPTOR = _LDMIDPOINT,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.LDmidpoint)
  ))
_sym_db.RegisterMessage(LDmidpoint)

LanePropType = _reflection.GeneratedProtocolMessageType('LanePropType', (_message.Message,), dict(
  DESCRIPTOR = _LANEPROPTYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.LanePropType)
  ))
_sym_db.RegisterMessage(LanePropType)

ObjectType = _reflection.GeneratedProtocolMessageType('ObjectType', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTTYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.ObjectType)
  ))
_sym_db.RegisterMessage(ObjectType)

ImageType = _reflection.GeneratedProtocolMessageType('ImageType', (_message.Message,), dict(
  DESCRIPTOR = _IMAGETYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.ImageType)
  ))
_sym_db.RegisterMessage(ImageType)

ObjAttrType = _reflection.GeneratedProtocolMessageType('ObjAttrType', (_message.Message,), dict(
  DESCRIPTOR = _OBJATTRTYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.ObjAttrType)
  ))
_sym_db.RegisterMessage(ObjAttrType)

EventType = _reflection.GeneratedProtocolMessageType('EventType', (_message.Message,), dict(
  DESCRIPTOR = _EVENTTYPE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.EventType)
  ))
_sym_db.RegisterMessage(EventType)

LabelRequest = _reflection.GeneratedProtocolMessageType('LabelRequest', (_message.Message,), dict(
  DESCRIPTOR = _LABELREQUEST,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.LabelRequest)
  ))
_sym_db.RegisterMessage(LabelRequest)

LabelResponse = _reflection.GeneratedProtocolMessageType('LabelResponse', (_message.Message,), dict(
  DESCRIPTOR = _LABELRESPONSE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.LabelResponse)
  ))
_sym_db.RegisterMessage(LabelResponse)

AlgoState = _reflection.GeneratedProtocolMessageType('AlgoState', (_message.Message,), dict(
  DESCRIPTOR = _ALGOSTATE,
  __module__ = 'AlgoInterface_pb2'
  # @@protoc_insertion_point(class_scope:Algorithms.AlgoState)
  ))
_sym_db.RegisterMessage(AlgoState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
